const loremIpsum = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eget massa venenatis ligula dictum interdum. Phasellus varius cursus arcu, aliquet suscipit nunc mollis nec. Etiam mattis ligula nibh. Suspendisse viverra aliquam luctus. Fusce faucibus nisi in augue iaculis, ut tincidunt lorem laoreet. Sed convallis leo mi, nec auctor nibh pharetra sit amet. Nullam lobortis mollis sapien, ut dignissim ligula lacinia ac. Vestibulum scelerisque lectus ut est tincidunt, non mollis nunc rhoncus. Cras elit diam, vulputate eget turpis vel, finibus sodales eros. Quisque in efficitur ante. Quisque efficitur consequat sollicitudin. Ut maximus justo ut nunc tincidunt sodales. In hac habitasse platea dictumst. Vivamus lacinia ipsum egestas tellus sollicitudin ullamcorper. Nunc eu nunc eget nisi rhoncus scelerisque. In ut venenatis tellus, in convallis mauris. Nulla hendrerit sollicitudin velit, ac auctor turpis commodo id. Donec egestas odio a risus molestie, vitae cursus magna venenatis. Morbi pulvinar congue dui, sed vulputate magna gravida sit amet. Suspendisse leo dolor, imperdiet eu nunc eu, suscipit imperdiet velit. Phasellus blandit pretium tellus et imperdiet. Praesent malesuada risus id vehicula ultricies. Fusce in lectus a mauris feugiat maximus nec quis ante. Nulla ultrices pulvinar mauris, in rutrum massa malesuada eget. Phasellus pharetra vestibulum diam, ac porta augue. Suspendisse potenti. Suspendisse sed justo at nisi faucibus volutpat. Duis ut sapien massa. Donec ac tincidunt ante. In egestas ex lacus. Aenean vel nibh commodo quam pulvinar tempus. Duis imperdiet, ligula et ultrices mollis, nibh est ullamcorper libero, sed efficitur augue ligula a quam. Vivamus iaculis, erat nec accumsan efficitur, ante ligula ullamcorper purus, vel condimentum dui enim quis neque. Integer leo ante, molestie in tristique quis, pretium sed est. Maecenas non urna nibh. Maecenas non ipsum tincidunt, aliquam eros nec, congue ante. Praesent sit amet nunc nec massa accumsan dapibus. Fusce lobortis mollis lectus, sit amet porttitor neque ullamcorper ut. Donec in ligula ut eros rhoncus varius. Quisque sed lectus sit amet odio porta feugiat consectetur at justo. Ut suscipit porttitor aliquet. Ut ornare lacus ac eros convallis mattis at at nunc. Morbi vitae elementum enim. Pellentesque gravida luctus ipsum, id pellentesque nisl eleifend sed. Maecenas consequat nisi vel arcu facilisis semper eu rutrum turpis. Maecenas vel lectus lobortis, volutpat eros eu, luctus neque. Curabitur id elit ac nisi tempus aliquet. Nullam tincidunt ante eget viverra iaculis. Morbi sodales odio vel neque lobortis pharetra. Maecenas sed dolor vel mi aliquam faucibus. Curabitur nec magna sem.`

const getLoremIpsum = (numSentences: number) => {
    // get random sentences from loremIpsum
    const sentences = loremIpsum.split(". ");
    const randomSentences = [];
    for (let i = 0; i < numSentences; i++) {
        randomSentences.push(sentences[Math.floor(Math.random() * sentences.length)]);
    }
    return randomSentences.join(". ") + ".";
}

export default getLoremIpsum;